import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { Waypoint } from 'react-waypoint';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { MinimalPosts } from '../components/minimal-posts';
import { PersonalHeader } from '../components/personal-theme-header';
import {
	MorePostsByPublicationDocument,
	MorePostsByPublicationQuery,
	MorePostsByPublicationQueryVariables,
	PageInfoFragment,
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

type Props = {
	publication: PublicationFragment;
	initialPosts: PostFragment[];
	initialPageInfo: PageInfoFragment;
};

export default function Index({ publication, initialPosts, initialPageInfo }: Props) {
	const [posts, setPosts] = useState<PostFragment[]>(initialPosts);
	const [pageInfo, setPageInfo] = useState<Props['initialPageInfo']>(initialPageInfo);
	const [loadedMore, setLoadedMore] = useState(false);

	const loadMore = async () => {
		const data = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			MorePostsByPublicationDocument,
			{
				first: 20,
				host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
				after: pageInfo.endCursor,
			},
		);
		if (!data.publication) {
			return;
		}
		const newPosts = data.publication.posts.edges.map((edge) => edge.node);
		setPosts([...posts, ...newPosts]);
		setPageInfo(data.publication.posts.pageInfo);
		setLoadedMore(true);
	};

	return (
		<AppProvider publication={publication}>
			<Layout>
				<Head>
					<title>{publication.title}</title>
					<meta
						name="description"
						content={
							publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`
						}
					/>
					<meta property="twitter:card" content="summary_large_image"/>
					<meta property="twitter:title" content={publication.displayTitle || publication.title || 'Hashnode Blog Starter Kit'} />
					<meta property="twitter:description" content={publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`} />
					<meta
						property="og:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<meta
						property="twitter:image"
						content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
					/>
					<script
						type="application/ld+json"
						dangerouslySetInnerHTML={{
							__html: JSON.stringify(addPublicationJsonLd(publication)),
						}}
					/>
				</Head>
				<div className="min-h-screen bg-gray-100 text-gray-800 dark:bg-gray-900 dark:text-gray-200">
					<header className="bg-white dark:bg-gray-800 shadow-sm">
						<div className="container mx-auto px-4 py-6 flex justify-between items-center">
							<h1 className="text-3xl font-bold">Sandeep Dev</h1>
							<nav>
								<ul className="flex space-x-4">
									<li>
										<a href="/" className="text-blue-500 hover:text-blue-700 dark:text-blue-300 dark:hover:text-blue-400">Home</a>
									</li>
									<li>
										<a href="/blog" className="text-blue-500 hover:text-blue-700 dark:text-blue-300 dark:hover:text-blue-400">Blog</a>
									</li>
									<li>
										<a href="/projects" className="text-blue-500 hover:text-blue-700 dark:text-blue-300 dark:hover:text-blue-400">Projects</a>
									</li>
									<li>
										<a href="/about" className="text-blue-500 hover:text-blue-700 dark:text-blue-300 dark:hover:text-blue-400">About</a>
									</li>
								</ul>
							</nav>
						</div>
					</header>
					<main className="container mx-auto px-4 py-12">
						<section className="text-center">
							<h2 className="text-4xl font-semibold mb-6">Welcome to My Blog</h2>
							<p className="text-lg mb-8">I share my thoughts, projects, and more. Stay tuned for updates!</p>
						</section>
						<section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
							{/* Render posts here */}
							{posts.length > 0 && <MinimalPosts context="home" posts={posts} />}
						</section>
						{!loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
							<button className="bg-white mt-8 px-4 py-2 rounded shadow-md" onClick={loadMore}>
								Load more
							</button>
						)}
						{loadedMore && pageInfo.hasNextPage && pageInfo.endCursor && (
							<Waypoint onEnter={loadMore} bottomOffset={'10%'} />
						)}
					</main>
					<footer className="bg-white dark:bg-gray-800 shadow-sm mt-12">
						<div className="container mx-auto px-4 py-6 text-center">
							<p className="text-gray-600 dark:text-gray-400">&copy; 2024 Sandeep Dev</p>
						</div>
					</footer>
				</div>
			</Layout>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
		GQL_ENDPOINT,
		PostsByPublicationDocument,
		{
			first: 20,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const publication = data.publication;
	if (!publication) {
		return {
			notFound: true,
		};
	}
	const initialPosts = (publication.posts.edges ?? []).map((edge) => edge.node);

	return {
		props: {
			publication,
			initialPosts,
			initialPageInfo: publication.posts.pageInfo,
		},
		revalidate: 1,
	};
};
